### PR TITLE
add support of #base and #include macros

### PR DESCRIPTION
**Pull request by XavierCHN**

### CODE REVIEW

**Comment by JulioC** [comment]
It's been a while since I last worked with anything using kv files, can you link me any real world example for the macro usage? Some file from Valve or any wiki entry would be perfect

Thanks!

**Comment by JulioC** [comment]
Checking the [wiki entry](https://developer.valvesoftware.com/wiki/KeyValues) I had referenced when working on this, it looks like the path param is inside quotes. Is the common case for Valve files to not use these quotes?

Maybe this code should take that in account, at least discarding any character that matches `"` or `'`

**Comment by XavierCHN** [comment]
At least when making DOTA2 mods, these quotes are not needed.

**Comment by XavierCHN** [comment]
This is an example which working fine in dota2 workshop tools.
```
#base creatures/boss_pudge/npc_dota_creature_boss_pudge.txt
#base creatures/boss_pudge/npc_dota_creature_boss_pudge_minipudge.txt
#base creatures/boss_nevermore/npc_dota_creature_boss_nevermore.txt
#base creatures/boss_nevermore/npc_dota_nevermore_requiem_treant.txt
#base creatures/boss_huskar/npc_dota_creature_huskar.txt
#base creatures/boss_bristleback/npc_dota_creature_boss_bristleback.txt
#base creatures/boss_bristleback/npc_dota_creature_boss_bristleback_guard.txt
#base creatures/boss_techies/npc_dota_creature_boss_techies.txt
#base creatures/boss_techies/npc_dota_creature_boss_techies_bomb.txt

"DOTAUnits"
{
	"dummy_unit"
	{
		"BaseClass"			"npc_dota_creature"
		"Model"				"models/development/invisiblebox.vmdl"
		"Ability1"			"dummy_unit_passive"
	}
}
```

**Comment by JulioC** [comment]
Sorry for taking so long, @XavierCHN!

**Pull request merged**
